service: mailgun-send

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: ap-southeast-1
  memorySize: 128
  timeout: 5
  endpointType: regional

  environment:
    MAILGUN_API_KEY: ${env:MAILGUN_API_KEY, ''}
    MAILGUN_DOMAIN_NAME: ${env:MAILGUN_DOMAIN_NAME, ''}

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: send
          method: post
          cors: true
